services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
     - postgres-dados:/vai/lib/postgresql/data
    networks:
     - network-geral

  server:
    build: ./backend
    container_name: server
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - network-geral

  web:
    build: ./frontend
    container_name: web
    depends_on:
      - server
    ports:
      - "8080:80"
    networks:
      - network-geral

volumes:
  postgres-dados:

networks: 
  network-geral: